// Log to console
console.log('Hello');
console.log(123);
console.log(true);
var greeting = 'Hello';
console.log(greeting);
console.log([1,2,3,4]);
console.log({a:1, b:2});
console.table({a:1, b:2});
console.error('This marks an error');
console.clear();
console.warn('this is a warning');
console.time('Hello');
console.log('hi');
console.log('hi');
console.log('hi');
console.log('hi');
console.log('hi');
console.log('hi');
console.timeEnd('Hello');
